package com.icounseling.domain.enumeration;

/**
 * The CategoryType enumeration.
 */
public enum CategoryType {
    ROMANCE, ARTS_PHOTOGRAPHY, BIOGRAPHIES_MEMOIRS, BUSINESS_INVESTING, CHILDREN_BOOKS, COOKBOOKS_FOOD, HISTORY, LOTERATURE_FICTION, MYSTERY_THRILLER_SUSPENSE, SCIENCE_FICTION_FANTASY, TEEN_YOUNG_ADULT_BOOKS
}
